name: Ci/Cd course devops
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conect ssh
        env:
            PRIVATE_KEY: ${{secrets.AWS_PEM}}
            HOSTNAME: ${{secrets.AWS_HOST}}
            USERNAME: ${{secrets.AWS_USER}}
        run: echo $PRIVATE_KEY